2024-08-10 09:04:21,446 INFO    MainThread:6108 [wandb_setup.py:_flush():76] Current SDK version is 0.17.5
2024-08-10 09:04:21,446 INFO    MainThread:6108 [wandb_setup.py:_flush():76] Configure stats pid to 6108
2024-08-10 09:04:21,451 INFO    MainThread:6108 [wandb_setup.py:_flush():76] Loading settings from C:\Users\cherr\.config\wandb\settings
2024-08-10 09:04:21,451 INFO    MainThread:6108 [wandb_setup.py:_flush():76] Loading settings from c:\Documents\UWM\PSYCH755\final_project\wandb\settings
2024-08-10 09:04:21,451 INFO    MainThread:6108 [wandb_setup.py:_flush():76] Loading settings from environment variables: {'notebook_name': 'disorder_NN.ipynb'}
2024-08-10 09:04:21,451 INFO    MainThread:6108 [wandb_setup.py:_flush():76] Inferring run settings from compute environment: {'program': '<python with no main file>'}
2024-08-10 09:04:21,451 INFO    MainThread:6108 [wandb_setup.py:_flush():76] Applying login settings: {}
2024-08-10 09:04:21,451 INFO    MainThread:6108 [wandb_setup.py:_flush():76] Applying login settings: {}
2024-08-10 09:04:21,451 INFO    MainThread:6108 [wandb_init.py:_log_setup():529] Logging user logs to c:\Documents\UWM\PSYCH755\final_project\wandb\run-20240810_090421-wfcjum27\logs\debug.log
2024-08-10 09:04:21,451 INFO    MainThread:6108 [wandb_init.py:_log_setup():530] Logging internal logs to c:\Documents\UWM\PSYCH755\final_project\wandb\run-20240810_090421-wfcjum27\logs\debug-internal.log
2024-08-10 09:04:21,451 INFO    MainThread:6108 [wandb_init.py:_jupyter_setup():475] configuring jupyter hooks <wandb.sdk.wandb_init._WandbInit object at 0x000002A83BC1DFD0>
2024-08-10 09:04:21,451 INFO    MainThread:6108 [wandb_init.py:init():569] calling init triggers
2024-08-10 09:04:21,451 INFO    MainThread:6108 [wandb_init.py:init():576] wandb.init called with sweep_config: {}
config: {}
2024-08-10 09:04:21,452 INFO    MainThread:6108 [wandb_init.py:init():619] starting backend
2024-08-10 09:04:21,452 INFO    MainThread:6108 [wandb_init.py:init():623] setting up manager
2024-08-10 09:04:21,452 INFO    MainThread:6108 [backend.py:_multiprocessing_setup():105] multiprocessing start_methods=spawn, using: spawn
2024-08-10 09:04:21,458 INFO    MainThread:6108 [wandb_init.py:init():631] backend started and connected
2024-08-10 09:04:21,463 INFO    MainThread:6108 [wandb_run.py:_label_probe_notebook():1334] probe notebook
2024-08-10 09:04:21,463 INFO    MainThread:6108 [wandb_init.py:init():720] updated telemetry
2024-08-10 09:04:21,463 INFO    MainThread:6108 [wandb_init.py:init():753] communicating run to backend with 90.0 second timeout
2024-08-10 09:04:22,647 INFO    MainThread:6108 [wandb_run.py:_on_init():2435] communicating current version
2024-08-10 09:04:22,774 INFO    MainThread:6108 [wandb_run.py:_on_init():2444] got version response upgrade_message: "wandb version 0.17.6 is available!  To upgrade, please run:\n $ pip install wandb --upgrade"

2024-08-10 09:04:22,774 INFO    MainThread:6108 [wandb_init.py:init():804] starting run threads in backend
2024-08-10 09:04:30,528 INFO    MainThread:6108 [wandb_run.py:_console_start():2413] atexit reg
2024-08-10 09:04:30,528 INFO    MainThread:6108 [wandb_run.py:_redirect():2255] redirect: wrap_raw
2024-08-10 09:04:30,528 INFO    MainThread:6108 [wandb_run.py:_redirect():2320] Wrapping output streams.
2024-08-10 09:04:30,528 INFO    MainThread:6108 [wandb_run.py:_redirect():2345] Redirects installed.
2024-08-10 09:04:30,528 INFO    MainThread:6108 [wandb_init.py:init():847] run started, returning control to user process
2024-08-10 09:04:30,528 INFO    MainThread:6108 [wandb_run.py:_config_callback():1382] config_cb None None {'epochs': 150, 'batch_size': 32, 'num_layers': 2, 'dropout_rate': 0.3, 'learning_rate': 0.001, 'units_layer_1': 64, 'units_layer_2': 32}
2024-08-10 09:04:30,555 INFO    MainThread:6108 [wandb_watch.py:watch():51] Watching
2024-08-10 09:04:30,556 ERROR   MainThread:6108 [util.py:get_module():277] Error importing optional module torch
Traceback (most recent call last):
  File "c:\Users\cherr\miniconda3\Lib\site-packages\wandb\util.py", line 243, in import_module_lazy
    return sys.modules[name]
           ~~~~~~~~~~~^^^^^^
KeyError: 'torch'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "c:\Users\cherr\miniconda3\Lib\site-packages\wandb\util.py", line 272, in get_module
    return import_module_lazy(name)
           ^^^^^^^^^^^^^^^^^^^^^^^^
  File "c:\Users\cherr\miniconda3\Lib\site-packages\wandb\util.py", line 247, in import_module_lazy
    raise ModuleNotFoundError
ModuleNotFoundError
2024-08-10 09:04:30,889 INFO    MainThread:6108 [jupyter.py:save_ipynb():372] not saving jupyter notebook
2024-08-10 09:04:30,889 INFO    MainThread:6108 [wandb_init.py:_pause_backend():440] pausing backend
2024-08-10 09:05:00,560 INFO    MainThread:6108 [wandb_init.py:_resume_backend():445] resuming backend
2024-08-10 09:05:07,877 INFO    MainThread:6108 [jupyter.py:save_ipynb():372] not saving jupyter notebook
2024-08-10 09:05:07,877 INFO    MainThread:6108 [wandb_init.py:_pause_backend():440] pausing backend
2024-08-10 09:05:30,014 INFO    MainThread:6108 [wandb_init.py:_resume_backend():445] resuming backend
2024-08-10 09:05:30,044 INFO    MainThread:6108 [jupyter.py:save_ipynb():372] not saving jupyter notebook
2024-08-10 09:05:30,044 INFO    MainThread:6108 [wandb_init.py:_pause_backend():440] pausing backend
2024-08-10 09:15:35,845 INFO    MainThread:6108 [wandb_init.py:_resume_backend():445] resuming backend
2024-08-10 09:15:35,851 INFO    MainThread:6108 [jupyter.py:save_ipynb():372] not saving jupyter notebook
2024-08-10 09:15:35,851 INFO    MainThread:6108 [wandb_init.py:_pause_backend():440] pausing backend
2024-08-10 09:15:37,385 INFO    MainThread:6108 [wandb_init.py:_resume_backend():445] resuming backend
2024-08-10 09:15:37,482 INFO    MainThread:6108 [jupyter.py:save_ipynb():372] not saving jupyter notebook
2024-08-10 09:15:37,482 INFO    MainThread:6108 [wandb_init.py:_pause_backend():440] pausing backend
